recipes-bsp: ti-sci-fw: Fix Deploy issue
- Currently both a53 and r5 machine confs tries to deploy ti-fs firmwares in deploy directory resulting in following error,
```

ERROR: mc:k3r5:ti-sci-fw-08.06.04-r4.0.psdk0 do_deploy: The recipe ti-sci-fw is trying to install files into a shared area when those files already exist.

```
To fix it, add do_deploy:k3r5[noexec] = "1" so that the ti-fs firmwares are only shipped by a53 machine conf and r5 machine conf does nothing.

Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>